### ISSUE TITLE
Update to latest versions from Conda-Forge

### ISSUE THREAD

**Issue by sodre** [AnacondaRecipes/tqdm-feedstock#1]
Would it be possible to update the tqdm packages to the more recent ones available in Conda-Forge?

Thank you!
Patrick

**Comment by jjhelmus** [comment]
tqdm 4.28.1 is available in `defaults` which is also the latest version available in `conda-forge` and on pypi.  Is there a particular version you are looking for?

**Comment by sodre** [comment]
@jjhelmus, I apologize for opening this. I was told offline that https://github.com/tqdm/tqdm/pull/641 had been merged into master and it was available in pypi/conda-forge but not on anaconda. ''

I forgot to verify that had been the case before I opened the issue.
